import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import '@mantine/notifications/styles.css';
import '@/style/global.css';

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from "@/provider/providers";
import SessionLoader from "@/provider/sessionLoader";
// import {SessionProvider} from "next-auth/react";
// import {wrapper} from "@/store/store";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <html lang="en">
          <body className={inter.className}>
                  <Providers>
                      <SessionLoader>
                          {children}
                      </SessionLoader>
                  </Providers>
          </body>
        </html>
  )
}

// export default wrapper.withRedux(RootLayout)
